# Generated by Django 4.0 on 2021-12-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaraunt',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=80)),
                ('phone', models.IntegerField()),
                ('work_time', models.SmallIntegerField()),
                ('close_time', models.SmallIntegerField()),
                ('book_every', models.SmallIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='TableType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('amount', models.SmallIntegerField()),
                ('restaraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaraunts.restaraunt')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('bookedTime', models.BigIntegerField()),
                ('tableType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaraunts.tabletype')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('restaraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaraunts.restaraunt')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaraunts.menucategory')),
            ],
        ),
    ]
