# Generated by Django 4.0 on 2021-12-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaraunts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaraunt',
            old_name='work_time',
            new_name='open_time',
        ),
        migrations.RenameField(
            model_name='tabletype',
            old_name='amount',
            new_name='persons',
        ),
        migrations.RemoveField(
            model_name='restaraunt',
            name='description',
        ),
        migrations.AlterField(
            model_name='restaraunt',
            name='book_every',
            field=models.SmallIntegerField(default=30),
        ),
    ]
