# Generated by Django 4.0 on 2021-12-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaraunts', '0003_alter_dish_id_alter_menucategory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaraunt',
            name='book_every',
            field=models.SmallIntegerField(default=30, null=True),
        ),
    ]
